Give args to serve and no need to quote them
canonical-webteam/generator-canonical-webteam pull request #19
Opened 2017-05-23 16:14 UTC by WillMoggridge

Adding the ability to pass arguments to serve, primarily for Tutorials so that it can serve a single file for testing and development. Such as `./run serve new-tutorial.md`.

This also required me to fix the need to quote arguments, so I did that too!

## QA

Checkout this PR for Tutorials: https://github.com/canonical-websites/tutorials.ubuntu.com/pull/208
Use this new ./run
Try `./run node yarn run serve examples` - No error!
Try `./run serve testing` - An error about testing not existing!

2017-05-23 17:01 UTC, nottrobin requested changes
The extra quotation marks break it for me.

2017-05-23 17:01 UTC, nottrobin commented on generators/run/templates/run
> +<% } %>    "node") node_run "${project}-node-$(date +'%s')" "'${*}'" ;;
I get:

``` bash
$ ./run node yarn run serve examples
docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: \"'yarn\": executable file not found in $PATH".
ERRO[0000] error getting events from daemon: context canceled 
```

Unless I remove the extra `'`s. Then it works. (`"'${*}'"` -> `"${*}"`)

2017-05-24 12:45 UTC, WillMoggridge commented on generators/run/templates/run
> +<% } %>    "node") node_run "${project}-node-$(date +'%s')" "'${*}'" ;;
Seems that is correct, I removed the `'`. Could have sworn it worked that way.

2017-05-24 12:57 UTC, nottrobin approved these changes
Works a charm :+1:

2017-05-24 12:57 UTC, merged