Include database in tests; add flake8 tests
canonical-webteam/generator-canonical-webteam pull request #23
Opened 2017-05-26 22:02 UTC by nottrobin

- Change the start_database function to check if the database is already
  running, rather than recreating it every time.
  This is so the tests can be run while the server is running, using the
  same database.
- Use the new version of the django image which contains flake8, and
  run flake8 as part of the test stage.

2017-06-13 16:21 UTC, WillMoggridge requested changes
Running on tutorials.ubuntu.com, having a bower.json, says:
```
Unable to find image 'bower:latest' locally
```
Looks like that node_run command changes was missed on it.

2017-06-13 16:21 UTC, WillMoggridge commented on generators/run/templates/run
> +        <% } else { %>node_run "${project}-serve" "--env PORT=${PORT} --publish ${PORT}:${PORT} ${detach}" yarn run serve
These lines are removing the `${run_serve_docker_opts}` used by demos, and the arguments (`${*}`) passed from `./run serve ./path/to/file` which is used on Tutorials.

2017-06-13 16:40 UTC, nottrobin commented on generators/run/templates/run
> +        <% } else { %>node_run "${project}-serve" "--env PORT=${PORT} --publish ${PORT}:${PORT} ${detach}" yarn run serve
Good point

2017-06-13 16:48 UTC, nottrobin commented
@WillMoggridge fixed both issues, I hope.

2017-06-19 09:37 UTC, WillMoggridge commented on generators/run/templates/run
>          <% } else { %>node_run "${project}-serve" "--env PORT=${PORT} --publish ${PORT}:${PORT} ${detach}" yarn run serve
Actually need `${run_serve_docker_opts}` on the standard line more than the django one but preferably consistently on all of them. 
:)

2017-06-19 09:38 UTC, WillMoggridge commented on generators/run/templates/run
> +        <% } else { %>node_run "${project}-serve" "--env PORT=${PORT} --publish ${PORT}:${PORT} ${detach}" yarn run serve
Actually need ${run_serve_docker_opts} on the standard line more than the django one but preferably consistently on all of them. 😃

2017-06-19 09:39 UTC, WillMoggridge commented on generators/run/templates/run
> +        <% } else { %>node_run "${project}-serve" "--env PORT=${PORT} --publish ${PORT}:${PORT} ${detach}" yarn run serve
Actually, we do need it on all of them equally, I got confused.

2017-06-19 09:40 UTC, nottrobin commented on generators/run/templates/run
> +        <% } else { %>node_run "${project}-serve" "--env PORT=${PORT} --publish ${PORT}:${PORT} ${detach}" yarn run serve
Ah. How would you feel about committing that change to this branch yourself? You're more likely to get it right.

2017-06-19 09:40 UTC, WillMoggridge commented on generators/run/templates/run
> +        <% } else { %>node_run "${project}-serve" "--env PORT=${PORT} --publish ${PORT}:${PORT} ${detach}" yarn run serve
Sure thing

2017-06-19 10:32 UTC, WillMoggridge commented
OK! I added that and it looks good otherwise. I'll just approve but not merge as I added a commit

2017-06-19 10:32 UTC, WillMoggridge approved these changes

2017-06-19 11:25 UTC, merged