Improve dependency management
canonical-webteam/generator-canonical-webteam pull request #60
Opened 2018-02-15 23:15 UTC by nottrobin

Now we literally hash all the dependency files after the dependencies
have been successfully installed, and if that hash changes in the
future, we update the dependencies. This should be much more robust.

In addition, we make sure node_module overrides only happen *after* the
dependency checking and installation step, so they don't mess up
dependency checking.

Fixes #59

QA
--

**Fault tolerance**

Run `./run clean`, then `./run build`. But cancel the command half-way through installing Yarn dependencies.

Now run `./run` - it should install dependencies again, and everything should work fine.

**Module overrides**

Get yourself a checkout of [vanilla-framework](https://github.com/vanilla-framework/vanilla-framework/) which contains an obvious change that will effect the styling of www.ubuntu.com (e.g. `body {font-size: 0.5em !important;}` in `build.scss`).

Now run the site with:

``` bash
./run --node-module $HOME/{path-to-projects-folder}/vanilla-framework
```

You should see that it didn't install dependencies again, but it's using your local version of Vanilla.

Now run simply:

``` bash
./run
```

You should see that it still didn't install dependencies again, but that it's now using the original version of Vanilla.

2018-02-15 23:36 UTC, anthonydillon requested changes
Looks good, nice idea. Few comments in the code.

2018-02-15 23:36 UTC, anthonydillon commented on CHANGES.txt
> +v2.6.3 (2018-02-15): Improved dependency checking
`v2.7.0`

2018-02-15 23:36 UTC, anthonydillon commented on generators/run/templates/run
> +            docker_run "" pip3 install --requirement requirements.txt
Shouldn't you regenerate the `pip_dependencies_hash` after you install?

2018-02-15 23:40 UTC, nottrobin commented
@anthonydillon great catches. Fixed.

2018-02-16 11:04 UTC, anthonydillon commented
Almost good but doesn't install new deps when the requirements change. 👎

2018-02-16 12:01 UTC, nottrobin commented
@anthonydillon fixed

2018-02-16 14:08 UTC, anthonydillon approved these changes
Worked a treat.

QA
- Checked out the latest www.ubuntu.com
- Ran `./run clean`
- Ran `./run` and cancelled half way
- Ran `./run` and it installed again
- Updated requests package in requirements.txt to version 2.18.2
- Ran `./run` and it rebuilt just the pip deps

2018-02-16 14:08 UTC, merged